version: "3.9"

services:
  app:
    build: .
    container_name: backend_app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./server/src/images:/app/server/src/images

  db:
    image: postgres
    container_name: db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data/

  bot-app:
    build: .
    container_name: bot_app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 4200:4200
