version: "3.9"

services:
  app:
    build: .
    container_name: app
    depends_on:
      - db

    env_file:
      - .env
    ports:
      - 4200:4200

  db:
    image: postgres

    env_file:
      - .env
    container_name: db_tg
    ports:
      - 5431:5431
